### ISSUE TITLE
Build macOS X binary releases

### ISSUE THREAD

**Issue by aquarapid** [planetscale/vitess-releases#17]
There have been requests for a Mac binary build, mostly so that users can run client-side tools like vtctlclient and vtexplain locally, and do not have to resort to running Linux docker images.

**Comment by Anders-PlanetScale** [comment]
Gary added cross-build target to vitess Makefile https://github.com/vitessio/vitess/blob/e813ada00a6792624a2e3f05fc330184e71112e2/Makefile#L82

We should build the Darwin bins and tar them up to include in the releases going forward it is available in the latest release at this time https://github.com/planetscale/vitess-releases/releases/tag/e813ada00a.

To make, run;
$ GOOS=darwin GOARCH=amd64 make cross-build

Then tar up the darwin_amd64 directory that gets created in ~/go/bin
I ended up renaming the tar file to match other release packages vitess-11.0.0_SNAPSHOT-e813ada00a_darwin_amd64.tar.gz and then sha256sum'd it to provide sha256 hash.
