### ISSUE TITLE
Using Vtorc，Primary is Dead，how can i do to let it failover normally

### ISSUE THREAD

**Issue by shizhibo2016** [planetscale/vitess-releases#33]
E0318 06:32:01.683227   51275 topology_recovery.go:800] AttemptRecoveryRegistration: keyspace keyspace_yy shard 0 has recently experienced a failover (of 10.1.9.91:17201) and is in active period. It will not be failed over again. You may acknowledge the failure on this cluster (-c ack-cluster-recoveries) or on 10.1.9.91:17201 (-c ack-instance-recoveries) to remove this blockage

**Comment by Anders-PlanetScale** [comment]
You can still use PRS or ERS with vtorc running. If you want automated fail-over via vtorc you have to have the durability policy for the keyspace set to` semi_sync` and you have to have vtorc global-recovery enabled.

**Comment by shizhibo2016** [comment]
> You can still use PRS or ERS with vtorc running. If you want automated fail-over via vtorc you have to have the durability policy for the keyspace set to` semi_sync` and you have to have vtorc global-recovery enabled.
Thanks，That is ok。

**Comment by shizhibo2016** [comment]
Close
